### PR TITLE
Replace non-ASCII punctuation (broke syntax before)

### PR DESCRIPTION
**Pull request by addiment**
Certain CSS snippets were broken due to using unicode special characters, specifically the `unicode-range` property of the `@font-face` at-rule. The schema had some inconsistencies in using special characters and regular ASCII, so I replaced those instances with their respective ASCII counterparts.

- Replaced U+201C/201D (left/right double quotation marks `“` `”`) with U+0022 (quotation mark `"`)
- Replaced U+2018/2019 (left/right single quotation marks `‘` `’`) with U+0027 (apostrophe `'`)
- Replaced U+2013 (en dash `–`) with U+002D (hyphen-minus `-`)

While the ASCII swap on quotation marks and parenthesis is mostly preference, the unicode hyphens *don't work* when used in the browser, which I believe warrants the change. From the W3C CSS fonts specification:
> If the next code point in text is U+002D HYPHEN-MINUS (-), consume it. Otherwise, this is an invalid \<urange\>, and this algorithm must exit.

[4.5. Character range: the 'unicode-range' descriptor](https://w3c.github.io/csswg-drafts/css-fonts-4/#unicode-range-desc)
[7.1. The \<urange\> type](https://w3c.github.io/csswg-drafts/css-syntax-3/#urange-syntax)

### CODE REVIEW

**Comment by addiment** [comment]
@microsoft-github-policy-service agree

**Comment by addiment** [comment]
any maintainers want to check this? @aeschli

**Review by sandy081 — APPROVED** [review]

**Comment by addiment** [comment]
Resolved the merge conflict (wasn't much to do), can I get another review?

**Comment by addiment** [comment]
Gonna mention since this might get lost in notification hell otherwise @sandy081

**Review by aeschli — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]

**Comment by aeschli** [comment]
Thanks @addiment!

**Pull request merged**
